2020-01-13 16:49:43,461 [Thread-2: 11524]C:\ProgramData\Anaconda3\lib\site-packages\django\core\servers\basehttp.py:log_message:124 INFO - "POST /gonghang/ HTTP/1.1" 200 16
2020-01-13 16:50:09,386 [Thread-2: 11424]C:\ProgramData\Anaconda3\lib\site-packages\django\core\servers\basehttp.py:log_message:124 INFO - "POST /gonghang/ HTTP/1.1" 200 14
2020-01-13 16:50:29,625 [Thread-2: 5000]C:\Users\Administrator\Desktop\fsdo\Gonghangguize\ghrule\views.py:post:41 INFO - hellll
2020-01-13 16:50:29,896 [Thread-2: 5000]C:\ProgramData\Anaconda3\lib\site-packages\django\core\servers\basehttp.py:log_message:124 INFO - "POST /gonghang/ HTTP/1.1" 200 14
2020-01-13 19:35:52,175 [Thread-2: 140571430250240]/home/dev-root/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py:response_for_exception:74 ERROR - Invalid HTTP_HOST header: '172.16.1.116:8000'. You may need to add '172.16.1.116' to ALLOWED_HOSTS.
2020-01-13 19:35:52,219 [Thread-2: 140571430250240]/home/dev-root/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 WARNING - "GET / HTTP/1.1" 400 62657
2020-01-13 19:35:52,849 [Thread-3: 140571421857536]/home/dev-root/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py:response_for_exception:74 ERROR - Invalid HTTP_HOST header: '172.16.1.116:8000'. You may need to add '172.16.1.116' to ALLOWED_HOSTS.
2020-01-13 19:35:52,878 [Thread-3: 140571421857536]/home/dev-root/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 WARNING - "GET /favicon.ico HTTP/1.1" 400 62699
2020-01-13 19:51:58,530 [Thread-2: 139892859549440]/home/dev-root/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py:get_response:93 WARNING - Not Found: /
2020-01-13 19:51:58,531 [Thread-2: 139892859549440]/home/dev-root/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 WARNING - "GET / HTTP/1.1" 404 2042
2020-01-13 19:51:58,616 [Thread-3: 139892851156736]/home/dev-root/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py:get_response:93 WARNING - Not Found: /favicon.ico
2020-01-13 19:51:58,616 [Thread-3: 139892851156736]/home/dev-root/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 WARNING - "GET /favicon.ico HTTP/1.1" 404 2093
